name:                 smt-lib
version:              0.0.2
visibility:           public
id:                   smt-lib-0.0.2-inplace
key:                  smt-lib-0.0.2-inplace
license:              BSD-3-Clause
maintainer:           Tom Hawkins <tomahawkins@gmail.com>
author:               Tom Hawkins <tomahawkins@gmail.com>
homepage:             http://tomahawkins.org
synopsis:             Parsing and printing SMT-LIB.
description:
    SMT-LIB is a common language used by many SMT solvers.
    This library provides an SMT-LIB AST with parsing and printing utilities.

category:             Language
abi:                  inplace
exposed:              True
exposed-modules:      Language.SMTLIB Language.SMTLIB.Lexer
import-dirs:
    /mnt/d/D_Study/ISCAS/projects/SMT/Parser_Comparison/external/haskell-0.0.2/dist-newstyle/build/x86_64-linux/ghc-9.4.7/smt-lib-0.0.2/build

library-dirs:
    /mnt/d/D_Study/ISCAS/projects/SMT/Parser_Comparison/external/haskell-0.0.2/dist-newstyle/build/x86_64-linux/ghc-9.4.7/smt-lib-0.0.2/build

library-dirs-static:
    /mnt/d/D_Study/ISCAS/projects/SMT/Parser_Comparison/external/haskell-0.0.2/dist-newstyle/build/x86_64-linux/ghc-9.4.7/smt-lib-0.0.2/build

dynamic-library-dirs:
    /mnt/d/D_Study/ISCAS/projects/SMT/Parser_Comparison/external/haskell-0.0.2/dist-newstyle/build/x86_64-linux/ghc-9.4.7/smt-lib-0.0.2/build

data-dir:
    /mnt/d/D_Study/ISCAS/projects/SMT/Parser_Comparison/external/haskell-0.0.2/.

hs-libraries:         HSsmt-lib-0.0.2-inplace
depends:
    array-0.5.4.0 base-4.17.2.0 directory-1.3.7.1
    polyparse-1.13.1-8281c0377f87481712f02e7e135903ccf69f8f8769a78ccdbdb199357e5a0160

haddock-interfaces:
    /mnt/d/D_Study/ISCAS/projects/SMT/Parser_Comparison/external/haskell-0.0.2/dist-newstyle/build/x86_64-linux/ghc-9.4.7/smt-lib-0.0.2/doc/html/smt-lib/smt-lib.haddock

haddock-html:
    /mnt/d/D_Study/ISCAS/projects/SMT/Parser_Comparison/external/haskell-0.0.2/dist-newstyle/build/x86_64-linux/ghc-9.4.7/smt-lib-0.0.2/doc/html/smt-lib
