#!/usr/bin/env python3
"""Render the paper's Table 1 (LaTeX tabular) from ``run_summary.csv``."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--summary-csv", required=True)
    ap.add_argument("--out-tex", required=True)
    args = ap.parse_args(argv)

    with open(args.summary_csv, newline="") as fh:
        summary = list(csv.DictReader(fh))

    body_rows = []
    for s in summary:
        body_rows.append(
            " & ".join([
                s["label"],
                s["adapter_status"].replace("_", "\\_"),
                f"{s['tests_passed']}/{s['tests_total']}",
                "\\checkmark" if s["first_pass_success"] == "true" else "--",
                str(s["adapter_loc"]),
                str(s["backend_loc"]),
                s["failure_category"].replace("_", "\\_"),
            ]) + r" \\"
        )
    body = "\n".join(body_rows)

    out = Path(args.out_tex)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "% Auto-generated by case_studies/rdl_prototyping/scripts/gen_table1.py\n"
        "\\begin{tabular}{lllllll}\n"
        "\\toprule\n"
        "Front-end & Adapter status & Tests passed & First pass & "
        "Adapter LoC & Backend LoC & Failure category \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    print(f"Wrote {args.out_tex}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
